/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultShopRouteImport } from './routes/vault.shop'
import { Route as VaultContactRouteImport } from './routes/vault.contact'
import { Route as VaultCheckoutRouteImport } from './routes/vault.checkout'
import { Route as VaultCartRouteImport } from './routes/vault.cart'
import { Route as VaultAboutRouteImport } from './routes/vault.about'
import { Route as VaultProductsSlugRouteImport } from './routes/vault.products.$slug'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultShopRoute = VaultShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => VaultRoute,
} as any)
const VaultContactRoute = VaultContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => VaultRoute,
} as any)
const VaultCheckoutRoute = VaultCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => VaultRoute,
} as any)
const VaultCartRoute = VaultCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => VaultRoute,
} as any)
const VaultAboutRoute = VaultAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => VaultRoute,
} as any)
const VaultProductsSlugRoute = VaultProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/vault': typeof VaultRouteWithChildren
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRoutesByTo {
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/vault': typeof VaultRouteWithChildren
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/vault'
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault/'
    | '/vault/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault'
    | '/vault/products/$slug'
  id:
    | '__root__'
    | '/vault'
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault/'
    | '/vault/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/shop': {
      id: '/vault/shop'
      path: '/shop'
      fullPath: '/vault/shop'
      preLoaderRoute: typeof VaultShopRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/contact': {
      id: '/vault/contact'
      path: '/contact'
      fullPath: '/vault/contact'
      preLoaderRoute: typeof VaultContactRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/checkout': {
      id: '/vault/checkout'
      path: '/checkout'
      fullPath: '/vault/checkout'
      preLoaderRoute: typeof VaultCheckoutRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/cart': {
      id: '/vault/cart'
      path: '/cart'
      fullPath: '/vault/cart'
      preLoaderRoute: typeof VaultCartRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/about': {
      id: '/vault/about'
      path: '/about'
      fullPath: '/vault/about'
      preLoaderRoute: typeof VaultAboutRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/products/$slug': {
      id: '/vault/products/$slug'
      path: '/products/$slug'
      fullPath: '/vault/products/$slug'
      preLoaderRoute: typeof VaultProductsSlugRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultAboutRoute: typeof VaultAboutRoute
  VaultCartRoute: typeof VaultCartRoute
  VaultCheckoutRoute: typeof VaultCheckoutRoute
  VaultContactRoute: typeof VaultContactRoute
  VaultShopRoute: typeof VaultShopRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultProductsSlugRoute: typeof VaultProductsSlugRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultAboutRoute: VaultAboutRoute,
  VaultCartRoute: VaultCartRoute,
  VaultCheckoutRoute: VaultCheckoutRoute,
  VaultContactRoute: VaultContactRoute,
  VaultShopRoute: VaultShopRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultProductsSlugRoute: VaultProductsSlugRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
