/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XLabRouteImport } from './routes/x-lab'
import { Route as XAdminRouteImport } from './routes/x-admin'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultShopRouteImport } from './routes/vault.shop'
import { Route as VaultContactRouteImport } from './routes/vault.contact'
import { Route as VaultCheckoutRouteImport } from './routes/vault.checkout'
import { Route as VaultCartRouteImport } from './routes/vault.cart'
import { Route as VaultAboutRouteImport } from './routes/vault.about'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as VaultProductsSlugRouteImport } from './routes/vault.products.$slug'

const XLabRoute = XLabRouteImport.update({
  id: '/x-lab',
  path: '/x-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const XAdminRoute = XAdminRouteImport.update({
  id: '/x-admin',
  path: '/x-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultShopRoute = VaultShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => VaultRoute,
} as any)
const VaultContactRoute = VaultContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => VaultRoute,
} as any)
const VaultCheckoutRoute = VaultCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => VaultRoute,
} as any)
const VaultCartRoute = VaultCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => VaultRoute,
} as any)
const VaultAboutRoute = VaultAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => VaultRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultProductsSlugRoute = VaultProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRouteWithChildren
  '/x-admin': typeof XAdminRoute
  '/x-lab': typeof XLabRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x-admin': typeof XAdminRoute
  '/x-lab': typeof XLabRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRouteWithChildren
  '/x-admin': typeof XAdminRoute
  '/x-lab': typeof XLabRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/vault/about': typeof VaultAboutRoute
  '/vault/cart': typeof VaultCartRoute
  '/vault/checkout': typeof VaultCheckoutRoute
  '/vault/contact': typeof VaultContactRoute
  '/vault/shop': typeof VaultShopRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/products/$slug': typeof VaultProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/shop'
    | '/sitemap.xml'
    | '/vault'
    | '/x-admin'
    | '/x-lab'
    | '/products/$slug'
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault/'
    | '/vault/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/shop'
    | '/sitemap.xml'
    | '/x-admin'
    | '/x-lab'
    | '/products/$slug'
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault'
    | '/vault/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/shop'
    | '/sitemap.xml'
    | '/vault'
    | '/x-admin'
    | '/x-lab'
    | '/products/$slug'
    | '/vault/about'
    | '/vault/cart'
    | '/vault/checkout'
    | '/vault/contact'
    | '/vault/shop'
    | '/vault/'
    | '/vault/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaultRoute: typeof VaultRouteWithChildren
  XAdminRoute: typeof XAdminRoute
  XLabRoute: typeof XLabRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x-lab': {
      id: '/x-lab'
      path: '/x-lab'
      fullPath: '/x-lab'
      preLoaderRoute: typeof XLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x-admin': {
      id: '/x-admin'
      path: '/x-admin'
      fullPath: '/x-admin'
      preLoaderRoute: typeof XAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/shop': {
      id: '/vault/shop'
      path: '/shop'
      fullPath: '/vault/shop'
      preLoaderRoute: typeof VaultShopRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/contact': {
      id: '/vault/contact'
      path: '/contact'
      fullPath: '/vault/contact'
      preLoaderRoute: typeof VaultContactRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/checkout': {
      id: '/vault/checkout'
      path: '/checkout'
      fullPath: '/vault/checkout'
      preLoaderRoute: typeof VaultCheckoutRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/cart': {
      id: '/vault/cart'
      path: '/cart'
      fullPath: '/vault/cart'
      preLoaderRoute: typeof VaultCartRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/about': {
      id: '/vault/about'
      path: '/about'
      fullPath: '/vault/about'
      preLoaderRoute: typeof VaultAboutRouteImport
      parentRoute: typeof VaultRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/products/$slug': {
      id: '/vault/products/$slug'
      path: '/products/$slug'
      fullPath: '/vault/products/$slug'
      preLoaderRoute: typeof VaultProductsSlugRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultAboutRoute: typeof VaultAboutRoute
  VaultCartRoute: typeof VaultCartRoute
  VaultCheckoutRoute: typeof VaultCheckoutRoute
  VaultContactRoute: typeof VaultContactRoute
  VaultShopRoute: typeof VaultShopRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultProductsSlugRoute: typeof VaultProductsSlugRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultAboutRoute: VaultAboutRoute,
  VaultCartRoute: VaultCartRoute,
  VaultCheckoutRoute: VaultCheckoutRoute,
  VaultContactRoute: VaultContactRoute,
  VaultShopRoute: VaultShopRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultProductsSlugRoute: VaultProductsSlugRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaultRoute: VaultRouteWithChildren,
  XAdminRoute: XAdminRoute,
  XLabRoute: XLabRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
